import React, { useState } from "react";
import "./App.css";
import GameCard from "./GameCard";
import games from "./games";

function App() {
  const [page, setPage] = useState("home");
    const [selectedGame, setSelectedGame] = useState(null);

      const viewGame = (game) => {
          setSelectedGame(game);
              setPage("details");
                };

                  const buyGame = () => {
                      setPage("checkout");
                        };

                          const confirmOrder = () => {
                              setPage("success");
                                };

                                  const backHome = () => {
                                      setSelectedGame(null);
                                          setPage("home");
                                            };

                                              return (
                                                  <div className="container">

                                                        {/* HOME PAGE */}
                                                              {page === "home" && (
                                                                      <div className="home">
                                                                                <h1>🎮GAMES SPOT </h1>

                                                                                          <p>
                                                                                                      COME LETS PLAY GUYSS
                                                                                                                </p>

                                                                                                                          <button
                                                                                                                                      className="btn"
                                                                                                                                                  onClick={() => setPage("games")}
                                                                                                                                                            >
                                                                                                                                                                        POLLAMAA FRIENDSS
                                                                                                                                                                                  </button>
                                                                                                                                                                                          </div>
                                                                                                                                                                                                )}

                                                                                                                                                                                                      {/* GAMES PAGE */}
                                                                                                                                                                                                            {page === "games" && (
                                                                                                                                                                                                                    <>
                                                                                                                                                                                                                              <h1>🎮GAMERS MEETING AREA</h1>

                                                                                                                                                                                                                                        <div className="game-grid">
                                                                                                                                                                                                                                                    {games.map((game) => (
                                                                                                                                                                                                                                                                  <GameCard
                                                                                                                                                                                                                                                                                  key={game.id}
                                                                                                                                                                                                                                                                                                  game={game}
                                                                                                                                                                                                                                                                                                                  onView={viewGame}
                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                            className="backBtn"
                                                                                                                                                                                                                                                                                                                                                                                        onClick={() => setPage("home")}
                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                              ←Back
                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                </>
                                                                                                                                                                                                                                                                                                                                                                                                                                      )}

                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* DETAILS PAGE */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                  {page === "details" && selectedGame && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="details">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h1>{selectedGame.image}</h1>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h2>{selectedGame.name}</h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h3>₹ {selectedGame.price}</h3>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p>{selectedGame.description}</p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="btn"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onClick={buyGame}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Buy Now
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="backBtn"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onClick={() => setPage("games")}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Back
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* CHECKOUT PAGE */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {page === "checkout" && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="checkout">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h1>💳 Checkout</h1>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h2>{selectedGame.image} {selectedGame.name}</h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <h3>Total : ₹ {selectedGame.price}</h3>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="btn"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={confirmOrder}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Confirm Purchase
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="backBtn"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={() => setPage("details")}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Back
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* SUCCESS PAGE */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {page === "success" && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="success">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <h1>🎉 Order Successful!</h1>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Thank you for purchasing
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <br />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <b>{selectedGame.name}</b>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="btn"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onClick={backHome}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Back To Home
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    export default App;